name: Lupra Prime APK Yapici

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Java Kurulumu
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter Kurulumu
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Proje İskeletini Oluştur
        run: |
          # Boş bir Flutter projesi yarat
          flutter create --org com.lupraprime .
          
          # WebView paketini ekle
          flutter pub add webview_flutter
          
          # Senin kodunu ana dosya ile değiştir
          rm lib/main.dart
          cp kod/main.dart lib/main.dart
          
          # Android İnternet İznini Otomatik Ekle
          sed -i 's/<application/<uses-permission android:name="android.permission.INTERNET"\/>\n    <application/g' android/app/src/main/AndroidManifest.xml
          
          # İkon Ayarları
          flutter pub get

      - name: APK Derle (Release Mod)
        run: flutter build apk --release --no-tree-shake-icons

      - name: APK'yı Yükle (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: lupra-prime-apk
          path: build/app/outputs/flutter-apk/app-release.apk
